config/routes.rb
Rails.application.routes.draw do
  resources :products

  # Start: *TODO: 
  # Devise
  devise_for :users,  controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: 'registrate' }
   
  
  
  #  get 'pages/home'
  #  get 'pages/terms'
  #  get 'pages/privacy'
  # Static Views
  get '/home',    to: 'pages#home'
  get '/terms',   to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  # Static Views 
  resources :contacts, only: %i[new create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  # End: *TODO:
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElectronicShowCaseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <!-- Start: *TODO: -->
    <!-- NAV LINK -->
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Terms", terms_path %></li>
        <li><%= link_to "Privacy", privacy_path %></li>
        <li><%= link_to "Contacts", new_contact_path %></li>
      </ul>
      <ul>
        <% if user_signed_in? %>
          <li>
            <strong><%= current_user.full_name %></strong> | <%= current_user.role %>
          </li>
          <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
          <li><%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Registrate", new_user_registration_path %></li>
          <li><%= link_to "Inicia sesión", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
    <!-- End: *TODO: -->

    <div class="container">

      <!-- Start: *TODO: -->
      <!-- flash messages -->
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
     <!-- End: *TODO: -->

      <%= yield %>
    </div>

  </body>
</html>